force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Heroes</relationshipLabel>
    <relationshipName>Heroes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SuperheroMission__c/SuperheroMission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuperheroMission__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Superhero Missions</relationshipLabel>
    <relationshipName>SuperheroMissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SuperheroMission__c/fields/IsPublic__c.field-meta.xml
<CustomField>
    <fullName>IsPublic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SuperheroMissionTriggerHandlerTest.cls
@IsTest
private class SuperheroMissionTriggerHandlerTest {

    @testSetup
    static void setup() {
        Account account = TestDataService.createAccount('Test Account');
        insert account;

        Contact contact = TestDataService.createContact('Test Contact', 'test@gmail.com', account.Id);
        insert contact;

        Id profileId = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus User'].Id;
        User communityUser = TestDataService.createCommunityUser(contact.Id, profileId, 'Test', 'CommunityUser');
        insert communityUser;

        Hero__c hero = TestDataService.createHero('Test hero', contact.Id);
        insert hero;

        Guild__c guild = TestDataService.createGuild('Test guild');
        insert guild;
    }

    @IsTest
    static void sendEmailAlertNewMissionTest() {
        Guild__c guild = [SELECT Id FROM Guild__c LIMIT 1];

        SuperheroMission__c superheroMission = TestDataService.createSuperheroMission('Test subject', guild.Id);
        superheroMission.IsPublic__c = true;

        Boolean isException = false;

		Test.startTest();
		try {
            insert superheroMission;
		} catch (Exception e) {
			isException = true;
		}
		Test.stopTest();

		System.assert(!isException, 'Email message should be sent without exeptions');
    }
}