force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SuperheroMission__c/SuperheroMission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuperheroMission__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Superhero Missions</relationshipLabel>
    <relationshipName>SuperheroMissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SuperheroMissionDAOTest.cls
@IsTest
private class SuperheroMissionDAOTest {

    @testSetup
    static void setup() {
        Guild__c guild = TestDataService.createGuild('Test guild');
        insert guild;

        SuperheroMission__c superheroMission = TestDataService.createSuperheroMission('Test subject', guild.Id);
        insert superheroMission;
    }

    @IsTest
    static void getByIdsTest() {
        SuperheroMission__c mission = [SELECT Id FROM SuperheroMission__c LIMIT 1];
        List<SuperheroMission__c> missionsResult = new SuperheroMissionDAO().getByIds(new List<Id>{ mission.Id });
        System.assert(!missionsResult.isEmpty(), 'Superhero Missions should be found');
    }
}