force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Heroes</relationshipLabel>
    <relationshipName>Heroes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MissionAssignment__c/MissionAssignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assignment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MissionAssignment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hero</label>
    <referenceTo>Hero__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>MissionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MissionAssignment__c/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mission</label>
    <referenceTo>SuperheroMission__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>MissionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MissionAssignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuperheroMission__c/SuperheroMission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuperheroMission__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Superhero Missions</relationshipLabel>
    <relationshipName>SuperheroMissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MissionAssignmentTriggerHandlerTest.cls
@IsTest
private class MissionAssignmentTriggerHandlerTest {

    @testSetup
    static void setup() {
        User user = [SELECT Id, Email FROM User WHERE Id = :UserInfo.getUserId()];
        user.Email = 'test.test@gmail.test';
        update user;

        Contact contact = TestDataService.createContact('Test contact');
        insert contact;

        Hero__c hero = TestDataService.createHero('Test hero', contact.Id);
        Hero__c hero2 = TestDataService.createHero('Test hero2', contact.Id);
        insert new List<Hero__c>{ hero, hero2 };
        
        Guild__c guild = TestDataService.createGuild('Test guild');
        insert guild;

        SuperheroMission__c superheroMission = TestDataService.createSuperheroMission('Test subject', guild.Id);
        insert superheroMission;

        MissionAssignment__c missionAssignment = TestDataService.createMissionAssignment(hero.Id, superheroMission.Id);
        MissionAssignment__c missionAssignment2 = TestDataService.createMissionAssignment(hero2.Id, superheroMission.Id);
        insert new List<MissionAssignment__c>{ missionAssignment, missionAssignment2 };
    }

    @IsTest
    static void setFailedStatusTest() {
        SuperheroMission__c superheroMission = [SELECT Id FROM SuperheroMission__c LIMIT 1];
        MissionAssignment__c missionAssignmentToUpdate = [SELECT Id, Status__c FROM MissionAssignment__c LIMIT 1];
        missionAssignmentToUpdate.Status__c = Constant.MISSION_ASSIGNMENT_STATUS_COMPLETED;
        update missionAssignmentToUpdate;

        MissionAssignment__c missionAssignment = [
            SELECT Id, Status__c
            FROM MissionAssignment__c 
            WHERE Mission__c = :superheroMission.Id
            AND Id != :missionAssignmentToUpdate.Id
        ];
        
        System.assert(missionAssignment.Status__c == Constant.MISSION_ASSIGNMENT_STATUS_FAILED, 
            'Mission Assignment Status should be updated to Failed');
    }

    @IsTest
    static void sendEmailToMissionCreatorTest() {
        SuperheroMission__c superheroMission = [SELECT Id FROM SuperheroMission__c LIMIT 1];
        MissionAssignment__c missionAssignmentToUpdate = [SELECT Id, Status__c FROM MissionAssignment__c LIMIT 1];
        missionAssignmentToUpdate.Status__c = Constant.MISSION_ASSIGNMENT_STATUS_COMPLETED;

        Boolean isException = false;

		Test.startTest();
		try {
            update missionAssignmentToUpdate;
		} catch (Exception e) {
			isException = true;
		}
		Test.stopTest();

		System.assert(!isException, 'Email message should be sent without exeptions');
    }
}