force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Heroes</relationshipLabel>
    <relationshipName>Heroes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hero__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Heroes</relationshipLabel>
    <relationshipName>Heroes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MissionAssignment__c/MissionAssignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assignment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MissionAssignment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hero</label>
    <referenceTo>Hero__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>MissionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MissionAssignment__c/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mission</label>
    <referenceTo>SuperheroMission__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>MissionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MissionAssignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuperheroMission__c/SuperheroMission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuperheroMission__c/fields/ComplexityRank__c.field-meta.xml
<CustomField>
    <fullName>ComplexityRank__c</fullName>
    <label>Complexity Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuperheroMission__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Superhero Missions</relationshipLabel>
    <relationshipName>SuperheroMissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AllMissionsController.cls
public with sharing class AllMissionsController {

    /**
     * description      get all Superhero Missions which are Public or have the same Guild as curren Hero
     * @return          List of Superhero Missions
     */
    @AuraEnabled
    public static List<MissionWrapper> getAllMissions() {

        List<User> users = [
            SELECT Id, ContactId
            FROM User
            WHERE ContactId != null
            AND Id = :UserInfo.getUserId()
        ];

        List<Id> contactIds = new List<Id>();
        for (User user : users) {
            contactIds.add(user.ContactId);
        }

        List<Hero__c> heroes = [
            SELECT Id, Contact__c
            FROM Hero__c
            WHERE Contact__c IN :contactIds
        ];

        List<Id> heroIds = new List<Id>();
        for (Hero__c hero : heroes) {
            heroIds.add(hero.Id);
        }

        List<SuperheroMission__c> missions = new List<SuperheroMission__c>([
            SELECT Id, ComplexityRank__c, Subject__c, Guild__r.Name,
                (
                    SELECT Status__c, Hero__c
                    FROM MissionAssignments__r
                    WHERE Hero__c IN :heroIds
                    LIMIT 1
                )
            FROM SuperheroMission__c
            ORDER BY CreatedDate DESC
        ]);
        
        List<MissionWrapper> missionsWrapper = new List<MissionWrapper>();
        for (SuperheroMission__c sm : missions) {
            MissionWrapper missionWrapper = new MissionWrapper();
            missionWrapper.id = sm.Id;
            missionWrapper.rank = sm.ComplexityRank__c;
            missionWrapper.subject = sm.Subject__c;
            missionWrapper.guildName = sm.Guild__r.Name;
            missionWrapper.status = !sm?.MissionAssignments__r.isEmpty() ? sm.MissionAssignments__r[0].Status__c : null;
            missionsWrapper.add(missionWrapper);
        }

        return missionsWrapper;
    }

    public class MissionWrapper {
        @AuraEnabled public String id;
        @AuraEnabled public String rank;
        @AuraEnabled public String subject;
        @AuraEnabled public String guildName;
        @AuraEnabled public String status;
    }
}