force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Heroes</relationshipLabel>
    <relationshipName>Heroes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hero__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Heroes</relationshipLabel>
    <relationshipName>Heroes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HeroDAO.cls
public with sharing class HeroDAO {

    /**
     * description      get Heroes with Contact Emails
     * @return          List Heroes
     */
    public List<Hero__c> getWithContactEmails() {
        return [
            SELECT Id, Contact__r.Email
            FROM Hero__c
            WHERE Contact__r.Email != null
        ];
    }

    /**
     * description          get Heroes with Contact Emails
     * @param  guilds       List of Guild Ids
     * @return              List Heroes
     */
    public List<Hero__c> getWithContactEmailsByGuilds(List<Id> guilds) {
        return [
            SELECT Id, Contact__r.Email
            FROM Hero__c
            WHERE Contact__r.Email != null
            AND Guild__c IN :guilds
        ];
    }
}