force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Heroes</relationshipLabel>
    <relationshipName>Heroes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hero__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Heroes</relationshipLabel>
    <relationshipName>Heroes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MissionAssignment__c/MissionAssignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assignment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MissionAssignment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hero</label>
    <referenceTo>Hero__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>MissionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MissionAssignment__c/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mission</label>
    <referenceTo>SuperheroMission__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>MissionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SuperheroMission__c/SuperheroMission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuperheroMission__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Superhero Missions</relationshipLabel>
    <relationshipName>SuperheroMissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SuperheroMission__c/fields/IsPublic__c.field-meta.xml
<CustomField>
    <fullName>IsPublic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestDataService.cls
@isTest
public class TestDataService {

    /**
     * description      creation of Account
     * @param  name     Last name of Contact
     * @return          Account
     */
    public static Account createAccount(String name) {
        Account portalAccount = new Account();
        portalAccount.Name = name;
        return portalAccount;
    }

    /**
     * description              creation of Contact
     * @param  lastName         Last name of Contact
     * @param  email            Email of Contact
     * @param  accountId        Id of Account
     * @return                  Contact
     */
    public static Contact createContact(String lastName, String email, Id accountId) {
        Contact portalContact = new contact();
        portalContact.LastName = lastName;
        portalContact.Email = email;
        portalContact.AccountId = accountId;
        return portalContact;
    }
    
    /**
     * description              creation of Contact
     * @param  lastName         Last name of Contact
     * @return                  Contact
     */
    public static Contact createContact(String lastName) {
        Contact contact = new contact();
        contact.LastName = lastName;
        return contact;
    }

    /**
     * description              creation of Hero
     * @param  name             Name of Hero
     * @param  contactId        Contact Id
     * @return                  Hero__c
     */
    public static Hero__c createHero(String name, Id contactId) {
        Hero__c hero = new Hero__c();
        hero.Name = name;
        hero.Contact__c = contactId;
        return hero;
    }

    /**
     * description      creation of Guild
     * @param  name     Name of Guild
     * @return          Guild__c
     */
    public static Guild__c createGuild(String name) {
        Guild__c guild = new Guild__c();
        guild.Name = name;
        return guild;
    }

    /**
     * description          creation of Superhero Mission
     * @param  subject      Subject of Superhero Mission
     * @param  guildId      Guild Id
     * @return              SuperheroMission__c
     */
    public static SuperheroMission__c createSuperheroMission(String subject, Id guildId) {
        SuperheroMission__c superheroMission = new SuperheroMission__c();
        superheroMission.Guild__c = guildId;
        superheroMission.Subject__c = subject;
        superheroMission.IsPublic__c = true;
        return superheroMission;
    }

    /**
     * description              creation of Mission Assignment
     * @param  heroId           Hero Id
     * @param  missionId        Mission Id
     * @return                  MissionAssignment__c
     */
    public static MissionAssignment__c createMissionAssignment(Id heroId, Id missionId) {
        MissionAssignment__c missionAssignment = new MissionAssignment__c();
        missionAssignment.Hero__c = heroId;
        missionAssignment.Mission__c = missionId;
        return missionAssignment;
    }

    /**
     * description      creation of Community User
     * @return          User
     */
    public static User createCommunityUser(String contactId, String profileId, String firstName, String lastName) {
        User user = new User();
        user.ProfileId = profileId;
        user.FirstName = firstName + String.valueOf(System.today());
        user.LastName = lastName;
        user.Email = 'test@test.com';
        user.Username = String.valueOf(System.today()) + '@gmail.com.test';
        user.Alias = 'alias';
        user.TimeZoneSidKey = 'America/Los_Angeles';
        user.LanguageLocaleKey = 'en_US';
        user.LocaleSidKey = 'en_US';
        user.EmailEncodingKey = 'UTF-8';
        user.ContactId = contactId;
        return user;
    }
}