force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MissionAssignment__c/MissionAssignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assignment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MissionAssignment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hero</label>
    <referenceTo>Hero__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>MissionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MissionAssignment__c/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mission</label>
    <referenceTo>SuperheroMission__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>MissionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MissionAssignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuperheroMission__c/SuperheroMission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/MissionAssignmentTriggerHandler.cls
public without sharing class MissionAssignmentTriggerHandler {
    private Map<Id, MissionAssignment__c> oldMap;
    private Map<Id, MissionAssignment__c> newMap;
    private List<MissionAssignment__c> newRecords;

    public MissionAssignmentTriggerHandler(Map<Id, MissionAssignment__c> oldMap, Map<Id, MissionAssignment__c> newMap, List<MissionAssignment__c> newRecords) {
        this.oldMap = oldMap;
        this.newMap = newMap;
        this.newRecords = newRecords;
    }

    public void afterUpdate() {
        setFailedStatus();
        sendEmailToMissionCreator();
    }

    /**
     * description      set Failed status to Missions of other Heroes when the Hero finished his Mission
     */
    private void setFailedStatus() {
        List<Id> heroIds = new List<Id>();
        List<Id> missionIds = new List<Id>();

        for (MissionAssignment__c mAssignment : this.newRecords) {
            if (this.oldMap.get(mAssignment.Id).Status__c != mAssignment.Status__c && 
                mAssignment.Status__c == Constant.MISSION_ASSIGNMENT_STATUS_COMPLETED) 
            {
                heroIds.add(mAssignment.Hero__c);
                missionIds.add(mAssignment.Mission__c);
            }
        }
        
        List<MissionAssignment__c> mAssignmentsToUpdate = new MissionAssignmentDAO().getByMissionAndHeroIds(heroIds, missionIds);
        if (!mAssignmentsToUpdate.isEmpty()) {
            for(MissionAssignment__c mAssignment : mAssignmentsToUpdate) {
                mAssignment.Status__c = Constant.MISSION_ASSIGNMENT_STATUS_FAILED;
            }

            update mAssignmentsToUpdate;
        }
    }

    /**
     * description      send Email to Mission creator once the Mission is Completed
     */
    private void sendEmailToMissionCreator() {
        List<Id> missionIds = new List<Id>();

        for (MissionAssignment__c mAssignment : this.newRecords) {
            if (this.oldMap.get(mAssignment.Id).Status__c != mAssignment.Status__c && 
                mAssignment.Status__c == Constant.MISSION_ASSIGNMENT_STATUS_COMPLETED) 
            {
                missionIds.add(mAssignment.Mission__c);
            }
        }

        if (!missionIds.isEmpty()) {
            List<String> emails = new List<String>();
            List<SuperheroMission__c> missions = new SuperheroMissionDAO().getByIds(missionIds);
            for (SuperheroMission__c mission : missions) {
                if (mission.Owner.Email != null) {
                    emails.add(mission.Owner.Email);
                }
            }
    
            if (!emails.isEmpty()) {
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                message.toAddresses = emails;
                message.subject = 'Mission is Completed';
                message.plainTextBody = 'The one of the Missions you have created is Completed!';

                List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage> { message };
                List<Messaging.SendEmailResult> sendEmailResults = Messaging.sendEmail(messages);

                if (!sendEmailResults[0].success) {
                    throw new EmailServiceException(sendEmailResults[0].errors[0].message);
                }
            }
        }
    }

    public class EmailServiceException extends Exception {
    }
}