force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heroes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MissionAssignment__c/MissionAssignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assignment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MissionAssignment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hero</label>
    <referenceTo>Hero__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>MissionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MissionAssignment__c/fields/Mission__c.field-meta.xml
<CustomField>
    <fullName>Mission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mission</label>
    <referenceTo>SuperheroMission__c</referenceTo>
    <relationshipLabel>Mission Assignments</relationshipLabel>
    <relationshipName>MissionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MissionAssignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MissionAssignmentDAO.cls
public with sharing class MissionAssignmentDAO {

    /**
     * description              get Mission Assignments by Hero and Mission Ids with In Progress status
     * @param  heroId           Hero Id
     * @param  missionId        Mission Id
     * @return                  List of Mission Assignments
     */
    public List<MissionAssignment__c> getByMissionAndHeroIds(List<Id> heroIds, List<Id> missionIds) {
        return [
            SELECT Id, Status__c, Hero__c, Mission__c
            FROM MissionAssignment__c
            WHERE Hero__c NOT IN :heroIds
            AND Mission__c IN :missionIds
            AND Status__c = :Constant.MISSION_ASSIGNMENT_STATUS_IN_PROGRESS
        ];
    }
}